[buildPlans.iosevka-marco-custom]
family  = "Iosevka Marco Custom"
design  = ["stress-fw", "ligset-coq", "v-l-zshaped", "v-i-zshaped", "v-zero-slashed", "v-at-long"]

[buildPlans.iosevka-marco-term-custom]
family  = "Iosevka Marco Term Custom"
design  = ["term", "v-l-zshaped", "v-i-zshaped", "v-zero-slashed", "v-at-long"]

